generic:
  error_message:
    access_denied: Access denied.
    required_field_not_provided: Required field not provided.
eves:
  block:
    error_message:
      unknown_signature_name: Unknown signature name.
  entity:
    error_message:
      an_entity_with_expression_already_exists: Another $entity with $expression already exists.
    column_equal_to_value: $column "$value"
  method_eve:
    error_message:
      unknown_request_item: Unknown request item.
      cannot_set_constant_request_item: Unknown request item.
services:
  expression_service:
    comma_separator: ", "
    conjunction_separator: ", and "
    disjunction_separator: ", or "
  date_time_instance:
    format:
      a:
        am: am
        pm: pm
      A:
        AM: AM
        PM: PM
      D:
        Sat: Sat
        Sun: Sun
        Mon: Mon
        Tue: Tue
        Wed: Wed
        Thu: Thu
        Fri: Fri
      F:
        gregorian:
          January: January
          February: February
          March: March
          April: April
          May: May
          June: June
          July: July
          August: August
          September: September
          October: October
          November: November
          December: December
        jalali:
          1: Farvardin
          2: Ordibehesht
          3: Khordad
          4: Tir
          5: Mordad
          6: Shahrivar
          7: Mehr
          8: Aban
          9: Azar
          10: Dey
          11: Bahman
          12: Esfand
      l:
        Saturday: Saturday
        Sunday: Sunday
        Monday: Monday
        Tuesday: Tuesday
        Wednesday: Wednesday
        Thursday: Thursday
        Friday: Friday
      M:
        gregorian:
          Jan: Jan
          Feb: Feb
          Mar: Mar
          Apr: Apr
          May: May
          Jun: Jun
          Jul: Jul
          Aug: Aug
          Sep: Sep
          Oct: Oct
          Nov: Nov
          Dec: Dec
        jalali:
          1: Far
          2: Ord
          3: Kho
          4: Tir
          5: Mor
          6: Sha
          7: Meh
          8: Aba
          9: Aza
          10: Dey
          11: Bah
          12: Esf
      S:
        st: st
        nd: nd
        rd: rd
        th: th
      f:
        0: Spring
        1: Summer
        2: Fall
        3: Winter
      p:
        gregorian:
          1: Ianuarius
          2: Februarius
          3: Martius
          4: Aprilis
          5: Maius
          6: Iunius
          7: Quintilis
          8: Sextilis
          9: September
          10: October
          11: November
          12: December
        jalali:
          1: Aries
          2: Taurus
          3: Gemini
          4: Cancer
          5: Leo
          6: Virgo
          7: Libra
          8: Scorpio
          9: Sagittarius
          10: Capricornus
          11: Aquarius
          12: Pisces
      q:
        0: Snake
        1: Horse
        2: Goat
        3: Monkey
        4: Rooster
        5: Dog
        6: Pig
        7: Rat
        8: Ox
        9: Tiger
        10: Rabbit
        11: Dragon
supers:
  files:
    generic:
      error_message:
        invalid_file: Invalid file.
        invalid_file_format: Invalid file format.
        invalid_file_size: File size is $size but must be at most $maxSize.
    image:
      error_message:
        min_width_violated: Image width is $width but must be at least $minWidth.
        max_width_violated: Image width is $width but must be at most $maxWidth.
        min_height_violated: Image height is $height but must be at least $minHeight.
        max_height_violated: Image height is $height but must be at most $maxHeight.
        ratio_violated: The image has the aspect ratio of $actualRatio but must have the aspect ratio of $formalRatio.
  highers:
    date:
      error_message:
        invalid_date: Invalid date $date.
    structured_map:
      error_message:
        unknown_key: Unknown key $key.
        unknown_keys: Unknown keys $keys.
        key_is_missing: The key $key is missing.
    timezone:
      error_message:
        invalid_timezone: Invalid timezone.
    set:
      error_message:
        invalid: Invalid value.
        invalid_values: Values $values are not in set $set.
  numerics:
    decimal_range:
      error_message:
        value_must_be_at_least_min: The value $value must be at least $min.
        value_must_be_at_most_max: The value $value must be at most $max.
    integer:
      error_message:
        value_is_not_an_integer: Value $value is not an integer.
        value_is_less_than_zero_therefore_is_not_unsigned: Value $value is less than zero and therefore is not unsigned.
  special:
    entity_relation:
      error_message:
        entity_with_id_does_not_exist: $entity with identifier $id does not exist.
        entity_does_not_exist: $entity does not exist.
  strings:
    text:
      error_message:
        type_is_not_string: $type is not string.
        length_must_be_at_least_min: Length of '$input' ($length) must be at least $min.
        length_must_be_at_most_max: Length of '$input' ($length) must be at most $max.
    enum:
      error_message:
        please_enter_a_valid_value_from_values: Please enter a valid value from values $values.
tools:
  signature_value_calculator:
    error_message:
      related_entity_with_id_is_already_in_rel: $entityRight with id $id is already in relationship with another $entityLeft.
      cannot_change_R11R_by_id: Cannot change a R11R relation by id.
      toOne_fields_cannot_include_id: ?-to-one fields cannot include id, if you want to change the id, don't add children to the field.
      toMany_fields_must_include_id: ?-to-many fields must include id.
methods:
  buffer:
    error_message:
      method_not_found: Method not found.
